### ISSUE TITLE
[BUG] AssertionError: All `columns` (['question']) must be present in `batch` (['train', 'validation']).

### ISSUE THREAD

**Issue by hitercs** [robustness-gym/robustness-gym#27]
**Describe the bug**
I run the demo code in the readme, it gives a bug:
AssertionError: All `columns` (['question']) must be present in `batch` (['train', 'validation']).

**To Reproduce**

```
# Get a dataset
from robustnessgym import Dataset
dataset = Dataset.load_dataset('boolq')

# Run the Spacy pipeline
from robustnessgym import Spacy
spacy = Spacy()
# .. on the 'question' column of the dataset
dataset = spacy(batch_or_dataset=dataset, 
                columns=['question'])
```

Include any relevant screenshots.

**Expected behavior**
Any solution to this question. 

**System Information**
 - OS: Linux
 - Versions for RG and relevant dependencies [`robustnessgym` (v0.0.3), `spacy` (v2.3.5)]

**Additional context**
Run the demo code in the readme.

**Comment by krandiash** [comment]
Hi, I'm working on updating documentation since I made a few breaking changes in the last release. I'll have notebooks and examples up by the end of this week that you can use to bootstrap your workflow. 

This problem is likely because `load_dataset` returns a dict of `Dataset` objects, since you don't pass in a particular split.

Instead, try running
```python
from robustnessgym import Dataset, Spacy
dataset = Dataset.load_dataset('boolq', split='validation') # grabs the validation split only, see Huggingface `datasets.load_dataset` for docs on this

spacy = Spacy()
dataset = spacy(dataset, ['question'])
```

Let me know if this goes through.
